spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    token:
      expirationMs: 3600000
      key: KZC8TnUHoFh4OdQR8D98nLZrsr3Js/I/EtrlQ7W826c=